#file: noinspection YAMLSchemaValidation
name: 'Run cppcheck'
description: 'Install and run cppcheck'

runs:
  using: "composite"
  steps:
    - name: Cache cppcheck
      uses: actions/cache/restore@v4
      id: cache-cppcheck
      with:
        key: ''
        path: ''


    - name: Build cppcheck
      shell: bash
      if: steps.cache-cppcheck.outputs.cache-hit != 'true'
      run: |
        bash ./scripts/build_cppcheck.sh -v ${CPPCHECK_VER}

    - name: Save cppcheck cache
      uses: actions/cache/save@v4
      if: steps.cache-cppcheck.outputs.cache-hit != 'true'
      with:
        key: ''
        path: ''


    - name: Install cppcheck
      shell: bash
      # this step is fast, no need for caching
      run: |
        cd cppcheck
        sudo cmake --install build

    # The flag CMAKE_EXPORT_COMPILE_COMMANDS generates compile_commands.json
    # which is used by cppcheck and clang-tidy
    - name: Configure CMake
      uses: ./.github/actions/configure-cmake
      with:


    - name: Cppcheck
      shell: bash
      run: |
        bash ./scripts/run_cppcheck.sh
